(function(){'use strict';const $=id=>document.getElementById(id);const esc=v=>window.SoloukiUtils?.escapeHtml?SoloukiUtils.escapeHtml(String(v??'')):String(v??'');function dates(){const t=new Date(),f=new Date();f.setDate(t.getDate()-29);$('fromDate').value=f.toISOString().slice(0,10);$('toDate').value=t.toISOString().slice(0,10)}function msg(t){$('msg').textContent=t||'';$('msg').hidden=!t}async function load(){msg('');$('rows').innerHTML='<tr><td colspan="7">جاري التحميل…</td></tr>';try{let q=SoloukiDB.sb().from('audit_logs').select('*').order('created_at',{ascending:false}).limit(500);const f=$('fromDate').value,to=$('toDate').value,a=$('action').value.trim();if(f)q=q.gte('created_at',f+'T00:00:00');if(to)q=q.lte('created_at',to+'T23:59:59');if(a)q=q.ilike('action_key','%'+a+'%');const {data,error}=await q;if(error)throw error;if(!data?.length){$('rows').innerHTML='<tr><td colspan="7">لا توجد عمليات ضمن النطاق المحدد.</td></tr>';return}$('rows').innerHTML=data.map(r=>`<tr class="card-row">`+
`<td data-label="التاريخ" dir="rtl">${esc(new Date(r.created_at).toLocaleString('ar-EG'))}</td>`+
`<td data-label="المستخدم">${esc(r.actor_name||r.actor_user_id||'—')}</td>`+
`<td data-label="الدور">${esc(r.actor_role||'—')}</td>`+
`<td data-label="العملية"><b>${esc(r.action_key)}</b></td>`+
`<td data-label="النوع">${esc(r.entity_type||'—')}</td>`+
`<td data-label="المعرف" dir="ltr" style="text-align:right">${esc(r.entity_id||'—')}</td>`+
`<td data-label="التفاصيل" class="audit-details">${esc(JSON.stringify(r.details||{},null,2))}</td>`+
`</tr>`).join('')}catch(e){msg('تعذر تحميل سجل التدقيق: '+(e.message||e));$('rows').innerHTML='<tr><td colspan="7">فشل التحميل.</td></tr>'}}async function init(){const s=await SoloukiSession.requireSession();if(!s)return;if(s.profile.role_type!=='superadmin'){alert('هذه الصفحة للمسؤول العام فقط.');location.href='dashboard.html';return}dates();$('refresh').onclick=load;$('logout').onclick=()=>SoloukiSession.logout();load()}init()})();
