(function(){
'use strict';
const $=id=>document.getElementById(id);
const esc=v=>window.SoloukiUtils?.escapeHtml?SoloukiUtils.escapeHtml(String(v??'')):String(v??'');
const state={profile:null};
function note(id,text){const e=$(id);e.textContent=text||'';e.hidden=!text;}
function iso(d){return d.toISOString().slice(0,10)}
function setDates(){const to=new Date(),from=new Date();from.setDate(to.getDate()-29);$('fromDate').value=iso(from);$('toDate').value=iso(to)}
function showProgress(t){$('progressText').textContent=t;$('progress').hidden=false}
function hideProgress(){$('progress').hidden=true}
function download(name,content,type){const blob=new Blob([content],{type});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function csv(rows){if(!rows.length)return '\ufeff';const cols=[...new Set(rows.flatMap(r=>Object.keys(r||{})))];const q=v=>'"'+String(v??'').replace(/"/g,'""')+'"';return '\ufeff'+cols.map(q).join(',')+'\r\n'+rows.map(r=>cols.map(c=>q(typeof r[c]==='object'?JSON.stringify(r[c]):r[c])).join(',')).join('\r\n')}
async function fetchAll(table, select='*', order='created_at', filters=[]){const out=[];const size=1000;for(let offset=0;;offset+=size){let q=SoloukiDB.sb().from(table).select(select).range(offset,offset+size-1);if(order)q=q.order(order,{ascending:false,nullsFirst:false});for(const f of filters)q=q[f.op](f.col,f.val);const {data,error}=await q;if(error)throw error;out.push(...(data||[]));if(!data||data.length<size)break;showProgress('تم تحميل '+out.length+' سجل من '+table+'…')}return out}
function dateFilters(col){const f=[];const from=$('fromDate').value,to=$('toDate').value;if(from)f.push({op:'gte',col,val:from});if(to)f.push({op:'lte',col,val:to+'T23:59:59'});return f}
async function build(){const students=await fetchAll('students','*','updated_at');const violations=await fetchAll('violation_records','*','violation_date',dateFilters('violation_date'));const merits=await fetchAll('merits','*','merit_date',dateFilters('merit_date'));const result={schema_version:'solouki-backup-1',app_version:window.SOLOUKI_CONFIG?.APP_VERSION||'',created_at:new Date().toISOString(),scope:{from:$('fromDate').value||null,to:$('toDate').value||null,account_scope:'RLS-visible-data'},students,violations,merits};if($('includeCatalogs').checked){showProgress('تحميل البيانات المرجعية…');const [catalog,locations,penalties,matrix]=await Promise.all([fetchAll('violations_catalog','*','id'),fetchAll('violation_locations','*','sort_order'),fetchAll('penalties','*','id'),fetchAll('degree_penalty_matrix','*','degree_id')]);result.catalog={violations_catalog:catalog,violation_locations:locations,penalties,matrix}}return result}
async function exportAction(kind){note('error','');note('ok','');showProgress('بدء التصدير…');try{if(kind==='students-csv'){const rows=await fetchAll('students','*','updated_at');download('solouki-students-'+iso(new Date())+'.csv',csv(rows),'text/csv;charset=utf-8');note('ok','تم إنشاء ملف الطلاب.'); if(window.SoloukiAudit) SoloukiAudit.record('export_students_csv','students',null,{rows:rows.length});return}if(kind==='violations-csv'){const rows=await fetchAll('violation_records','*','violation_date',dateFilters('violation_date'));download('solouki-violations-'+iso(new Date())+'.csv',csv(rows),'text/csv;charset=utf-8');note('ok','تم إنشاء ملف المخالفات.'); if(window.SoloukiAudit) SoloukiAudit.record('export_violations_csv','violation_records',null,{rows:rows.length});return}if(kind==='merits-csv'){const rows=await fetchAll('merits','*','merit_date',dateFilters('merit_date'));download('solouki-merits-'+iso(new Date())+'.csv',csv(rows),'text/csv;charset=utf-8');note('ok','تم إنشاء ملف التكريمات.'); if(window.SoloukiAudit) SoloukiAudit.record('export_merits_csv','merits',null,{rows:rows.length});return}const data=await build();download('solouki-backup-'+new Date().toISOString().replace(/[:.]/g,'-')+'.json',JSON.stringify(data,null,2),'application/json;charset=utf-8');note('ok','تم إنشاء النسخة JSON بنجاح.'); if(window.SoloukiAudit) SoloukiAudit.record('export_json','backup',null,{students:data.students.length,violations:data.violations.length,merits:data.merits.length});}catch(e){console.error(e);note('error','تعذر التصدير: '+(e.message||e));}finally{hideProgress()}}
async function init(){try{const session=await SoloukiSession.requireSession();if(!session)return;state.profile=session.profile||session;const allowed=state.profile.role_type==='superadmin'||await SoloukiPerms.canView('view_reports');if(!allowed){alert('ليست لديك صلاحية التصدير.');location.href='dashboard.html';return}setDates();document.querySelectorAll('[data-export]').forEach(b=>b.addEventListener('click',()=>exportAction(b.dataset.export)));}catch(e){note('error',e.message||'تعذر التحقق من الجلسة.')}}
init();
})();
